const errorLog = {
  InvalidName:
    "Name should be of minimum 2 length which contains only alphabets and white spaces",
  InvalidEmail: "Please enter a valid email address",
  InvalidType: "Please enter a valid type",
  InvalidName: "Please Title",
  InvalidTestId: "Please provide valid test id.",
  InvalidQuestionId: "Please provide a valid question id.",
  UserNotExist: "User does not exist",
  CannotUpdateProfilePicture: "Cannot update profile picture successfully",
  AdminConfigurationMissing: 'No configuration found for creating assessment particular course from admin side ',
  InvalidString: "Invalid string",
  InvalidNumber: "Invalid number",
  InvalidDate: "Invalid date",
  InvalidTime: "Invalid time",
  RequiredUserId: "Required user id.",
  EmailRequired: "Email is required",
  ApplicationTypeDeviceToken:
    "Both application_type and device_token are required",
  ApplicationTypeRequired:
    "Application type is required",
  FeedbackNotFound: 'User feedback not found',
  EnquiryNotFound: 'User enquiry not found',
  CannotCreate: "Cannot create entity",
  VerifyFirst: "Please verify your account first",
  ImageSizeError: "Image should be less than 5 mb",
  ImageSizeFunctionError: function (value) { return `Image size exceeds the allowed ${value} mb` },
  ImageFormatIncorrect: "Image upload format is not correct",
  InvalidPassword:
    "Password should be of minimum 1 uppercase, 1 lowercase, 1 digit, 1 alphanumeric character and total min 8 length",
  WrongAccessToken: "Wrong access token",
  ExpiredAccessToken: "Access token has been expired",
  PasswordRequired: "Password is required",
  RenewMembership: 'Please renew or upgrade your membership plan',
  AddressDetailsRequired: 'Please update all your address details [address line 1, city ,state ,pincode ,country] for completing stripe payments',
  InvalidLoginEmail: "Invalid email.Enter correct email",
  AccessDenied: "Access denied",
  InvalidLoginPassword: "Invalid password. Enter correct password",
  AssessmentAccessDenied: "Access denied for creating more than 2 assessments",
  AdminNotExist: "Admin does not exist",
  PasswordUpdateSuccess: "Your password has been updated successfully",
  InvalidCredentials: "Invalid credentials",
  InvalidFirstName:
    "First name should be of minimum 2 lengths which contains only alphabets and white spaces",
  TestNotFound: 'Quiz not found',
  AssessmentNotFound: 'Assessment not found',
  InvalidLastName: "Please give a valid last name",
  InvalidCountryCode: "Please select a valid country code",
  InvalidCountryCodeIso: "Please select a valid country ISO code",
  InvalidContactNumber: "Please enter a valid contact number",
  InvalidId: "Please enter a valid  id",
  InvalidPhoneNumber: "Please enter a valid phone number",
  InvalidCountryName: "Please select a valid country name",
  InvalidMembership: "No active membership found",
  BuyMembership: 'Purchase a membership plan',
  DeactivationTime: function (value) { return `Your account will be closed on ${value}. This is irreversible, your data is not recoverable and if you would like to continue using our services, you must create a new account` },
  AlreadyDeactivatedRequest: `Your request to deactivate account has already been initiated`,
  InvalidTestResetCount: 'Your limit of one test reset has already been used in your current membership',
  InvalidMembershipTimeLeft: 'You are not eligible for data reset',
  InvalidAvailability: "Please enter a valid availability status",
  InvalidVerifiedParam: "Please give a valid verify param",
  InvalidStatusId: "Please give a valid status id",
  InvalidUserId: "Unable to identify user. Please try again",
  InvalidAddressLine1: "Please enter a valid address line 1",
  InvalidAddressLine2: "Please enter a valid address line 2",
  InvalidCity: "Please enter a valid city",
  InvalidPincode: "Please enter a valid pincode",
  InvalidBio: "Please enter a valid bio",
  InvalidRoleName: "Please give a valid role name",
  InvalidEnquiryId: "Unable to identify enquiry. Please try again",
  InvalidDescription: "Please enter a valid description",
  InvalidSubject: "Please enter a valid subject id",
  InvalidTitle: "Please enter a valid title",
  InvalidProductId: "Please choose a valid Product",
  InvalidPrice: "Please enter a valid price",
  AnswerNotFound: "Answer not found",
  RequiredCurrenyFormat: "Required currency format",
  InvalidSlug: "Please give a valid slug",
  InvalidContent: "Please give a valid content",
  InvalidToken: "Plese give a valid token",
  InvalidPageNumber: "Please enter a valid page number",
  InvalidNumberOfRows: "Please enter a valid number of rows",
  InvalidPageNumberAndRows: "Please enter a valid page number & number of rows",
  InvalidSearchText: "Please enter a valid search text",
  InvalidDeviceToken: "Please give a valid device token",
  FirstNameRequired: "First name is required",
  FullNameRequired: "Full name is required",
  ProfilePictureRequired: "Profile picture is required",
  CountryCodeRequired: "Country dial code is required",
  InvalidCountryCode: "Country dial code should be less than 5 characters",
  CountryIsoCodeRequired: "Country iso code is required",
  InvalidGender: "Invalid gender selected",
  InvalidContactNumber: "Contact number should be less than 15 characters",
  InvalidAgeGroup: "Invalid age group selected",
  InvalidStudyTimePeriod: "Invalid study time period selected",
  InvalidGoalWithUs: "Invalid goal selection",
  InvalidGender: "Invalid selection",
  InvalidGender: "Invalid gender selected",
  AddressLine1Required: "Address line 1 is required",
  InvalidValueTerms: "Terms & condition should be from 0,1,true,false",
  InvalidValueIsActive: "is_active should be from 0,1,true,false",
  TokenRequired: "Auth token is required",
  DuplicateEmail: "Invalid, this Email is already registered. Please login",
  DuplicateContactNumber: "Invalid, this Phone number is already registered.",
  TokenExpiredOrWrong: "Invalid token or email verification link is expired",
  InvalidCourseEnrollType:
    'Course enrol type should be from "PURCHASED", "PURCHASE_VIA_COUPON", "ON_TRIAL", "GIFTED", "GIVEAWAY"',
  RequiredCourseEnrollType: "Course enroll type is required",
  RequiredCourseStartedDate: "Course Started Date is required",
  RequiredCourseId: "Course id is required",
  RequiredPageTitle: "Page title is required",
  RequiredPlanTitle: "Plan title is required",
  InvalidDurationType: 'Please provide valid duration type as month or days',
  RequiredPlanId: 'Please provide valid plan id',
  RequiredQuestionCalenderReminder: "Number of questions is required",
  RequiredFlashcardTitle: "Flashcard title is required",
  RequiredPlanDuration: "Plan duration is required",
  RequiredPageContent: "Page content is required",
  RequiredSubjectTitle: "Subject title is required",
  RequiredCourseTitle: "Course title is required",
  RequiredNoteTitle: "Note title is required",
  RequiredQuestionName: "Question name is required",
  RequiredQuestionText: "Question text is required",
  RequiredBookCategoryName: "Book category name is required",
  RequiredBookCategoryIcon: "Book category icon is required",
  RequiredChapterTitle: "Chapter title is required",
  RequiredAlertTitle: "Alert title is required",
  RequiredNewsTitle: "News title is required",
  RequiredBookTitle: "Book title is required",
  RequiredLessonTitle: "Lesson title is required",
  RequiredNewsDescription: "News description is required",
  RequiredAlertDescription: "Alert description is required",
  RequiredQuestionNoteTitle: "Question Note title is required",
  RequiredNoteText: "Note text is required",
  RequiredQuestionNoteText: "Question Note text is required",
  RequiredCourseId: "Course id is required",
  RequiredTestModeId: "Quiz mode id is required",
  RequiredTestId: "Quiz id is required",
  RequiredCalendarReminderId: "Calendar reminder id is required",
  RequiredBookmarkId: "Bookmark id is required",
  InvalidPlanId: "Invalid plan id given",
  InvalidCourseCategoryId: "Invalid course category id given",
  InvalidCourseId: "Invalid category id given",
  RequiredBookId: "Book id is required",
  RequiredBookCourseId: "Book and course id is required",
  RequiredBookCategoryId: "Book category id is required",
  RequiredChapterId: "Chapter id is required",
  RequiredAlertId: "Alert id is required",
  InvalidAlertId: "Invalid alert id ",
  RequiredQuestionId: "Question id is required",
  BothAssessmentAndTest: 'Assessment and test id both given',
  RequiredAssessmentId: 'Required Assessment id',
  InvalidAssessmentId: 'Assessment not found',
  RequiredQuestionFeedbackId: "Question feedback id is required",
  RequiredSubjectId: "Subject id  array is required",
  RequiredQuestionTypeId: "Question type id is required",
  SubjectRequired: "Required feedback subject",
  AdaptiveFeedbackMessageRequired: "Required adaptive feedback message",
  QuestionFeedbackMessageRequired: "Required question feedback message",
  RequiredCourseCategoryId: "Course category id is required",
  RequiredCourseId: "Course id is required",
  RequiredFlashcardFrontText: "Flashcard front side is required",
  RequiredQuestionModeId: "Question mode id is required",
  RequiredLessonId: "Lesson id is required",
  RequiredFlashcardDeckId: "Flashcard deck id is required",
  RequiredLessonTopicId: "Lesson topic id is required",
  RequiredTotalQuestions: "Total number of questions is required",
  RequiredFlashcardBackText: "Flashcard back side is required",
  InvalidColor: "Invalid color given",
  InvalidChapterId: "Invalid chapter id given",
  RequiredColor: "Color is required",
  RequiredFlashcardId: "Flashcard id is required",
  RequiredNoteId: "Note id is required",
  RequiredNewsId: "News id is required",
  RequiredNewsSlug: "News slug is required",
  RequiredQuestionNoteId: "Question note id is required",
  RequiredFeedbackId: "Feedback id is required",
  CourseCategoryNameRequired: "course category name is required",
  RequiredChapterContent: "Chapter content is required",
  InvalidDuration: "Invalid duration given",
  RequiredDurationField: "Duration field is required",
  RequiredAudio: "Audio file is required",
  RequiredVideo: "Video file is required",
  RequiredPdf: "Pdf file is required",
  PageNotFound: "Page not found",
  BookmarkNotFound: "Bookmark not found",
  SectorNotFound: "Sector not found",
  LessonNotFound: "Lesson not found",
  LessonTopicNotFound: "Lesson topic not found",
  TestModeNotFound: "Quiz mode not found",
  QuestionTypeNotFound: "Question type not found",
  BookNotFoundForCourse: "Book not found for particular course",
  InvalidReminderId: "Invalid calendar reminder",
  InvalidBookId: "Invalid book id",
  InvalidChapterId: "Invalid chapter id",
  InvalidBookCategoryId: "Invalid book category id",
  InvalidTimeSelected:
    "Time selection has passed, select time in the future",
  InvalidEndTimeSelected:
    "End Time selection has passed, select a time in the future",
  InvalidEndTime:
    "End Time selection is less than start time selection",
  InvalidEndDate:
    "End Date selection is less than start date selection",
  InvalidStartDate:
    "Start Date selection is invalid, select a different start date",
  IncorrectVideoType: "Video upload format is not correct",
  IncorrectAudioType: "Audio upload format is not correct",
  IncorrectImageType: "Image upload format is not correct",
  AlertNotFound: "Alert not found",
  AccountDeactivated: 'Your account is now closed. This is irreversible, your data is not recoverable and if you would like to continue using our services, you must create a new account',
  CalendarReminderNotFound: "Calendar reminder not found",
  CalendarReminderTimePassed: "Calendar reminder cannot be edited",
  BookCategoryNotFound: "Book category not found",
  BookCategoryPresent: "Book category already present",
  CourseCategoryPresent: "Course category already found",
  NewsTitlePresent: "News with title already found",
  CoursePresent: "Course already present",
  BookPresent: "Book already present",
  QuestionfeedbackNotFound: "Question feedback not found",
  BookmarkNotFound: "Bookmark not found",
  CourseCategoryNotFound: "Course category not found",
  CourseNotFound: "Course not found",
  CourseNotStarted: "Course not started",
  PlansFound: "Plans for particular course started",
  ChapterNotFound: "Chapter not found",
  PlanNotFound: 'Plan not found',
  PlanDescriptionLengthExceeded: 'Plan description should be less than 500 characters.',
  PlanFound: 'Plans already found for particular course',
  FreePlanFound: 'Free Plan already found',
  SubjectNotFound: "Subject not found",
  SubjectForCourseNotFound: "Subject not found for particular course",
  FlashcardNotFound: "Flashcard not found",
  FlashcardDeckFound: "Flashcard Deck AlreadyPresent",
  FlashcardDeckNotFound: "Flashcard deck not found",
  NewsNotFound: "News not found",
  NoteNotFound: "Note not found",
  QuestionNoteNotFound: "Question note not found",
  QuestionNotFound: "Question not found",
  BookCategoryNotFound: "Book category not found",
  subscribeMembership:
    "Upgrade membership plan for further access",
  subscribeMembershipForAssessments:
    "Upgrade membership plan for further access to assessments",
  subscribeFreeOrPaidMembership:
    "Upgrade membership plan for further access",
  BookmarkFound: "Quiz question already bookmarked",
  BookmarkDeleted: "Bookmark deleted successfully",
};

module.exports = { errorLog };
